name: Latest Medium Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün 00:00'da çalışır
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Medium Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@m.enver.akkoc"
